apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.ports.mysql }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}